import os
from dotenv import load_dotenv

load_dotenv()

TEST_VEHICLE_NAME = os.getenv("TRACKOFY_TEST_VEHICLE", "GCBL10536MHG26DG08215")
REPORT_TEST_VEHICLE_NAME = os.getenv("TRACKOFY_REPORT_TEST_VEHICLE", "GCBL10536MHG14AG04459")
REPORT_TEST_DRIVER_NAME = os.getenv("TRACKOFY_REPORT_TEST_DRIVER", "syam")
REPORT_START_DATE = os.getenv("TRACKOFY_REPORT_START_DATE", "03/01/2026")
REPORT_END_DATE = os.getenv("TRACKOFY_REPORT_END_DATE", "03/10/2026")